package com.agentgierka.mmo.agent.model;

import com.agentgierka.mmo.player.Player;
import com.agentgierka.mmo.world.Location;
import jakarta.persistence.*;
import lombok.*;

import java.util.UUID;

/**
 * Represents an autonomous character (Agent) directed by player intent or AI.
 * Agents perform activities asynchronously in the game world.
 */
@Entity
@Table(name = "agents")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Agent {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "player_id")
    private Player owner;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id")
    private Location currentLocation;

    private Integer x;
    private Integer y;

    private Integer targetX;
    private Integer targetY;

    private Integer strength;
    private Integer dexterity;

    @Enumerated(EnumType.STRING)
    private AgentStatus status;

    /**
     * Narrative context describing the current scene or activity generated by AI.
     */
    private String currentActionDescription;
}
